### ISSUE TITLE
Question about current status.

### ISSUE THREAD

**Issue by hengjiUSTC** [RFRIEDM-Trimble/serial-ros2#1]
Great to see a galactic version here. Just hope to check is the master branch have the working version that we could use?

**Comment by RFRIEDM-Trimble** [comment]
Yep, that's correct, master. I'm focusing my efforts though on the `asio` async version of this library, which can be seen here: 
https://github.com/RFRIEDM-Trimble/serial-port

I'll be leaving this up regardless.
